### ISSUE TITLE
Idea: All changes since specific date

### ISSUE THREAD

**Issue by S1SYPHOS** [texnixe/kirby-logger#10]
Title says it all .. Often I just want to check what happened since the last time I visited (on one page) without copying it together from multiple pages. What do you think?

Useful plugin, really like it!

**Comment by texnixe** [comment]
Hm, in theory that would be easy. But how would I know when a user was logged in the last time? Or do you want to enter a specific date manually?

**Comment by S1SYPHOS** [comment]
Well, I'd simply enter the date I last checked for changes - totally manually, assisted only by the date picker 🔆

**Comment by S1SYPHOS** [comment]
It's been a while, might as well close the issue.
