### ISSUE TITLE
Role hardcoded instead of changeable in config

### ISSUE THREAD

**Issue by svnt** [texnixe/kirby-logger#6]
Hello,

it would be nice to have the option to set the role(s) for the widget/plugin in the kirby config instead of the hardcoded solution: https://github.com/texnixe/kirby-logger/search?utf8=✓&q=Admin&type=

In my case only 'auditors' should see it so i had to hack your core code.

best regards,
Sven

**Comment by texnixe** [comment]
This is now possible via the `logger.roles`option which accepts an array of options, see readme.
