### ISSUE TITLE
Order when sorting by date desc

### ISSUE THREAD

**Issue by malvese** [texnixe/kirby-logger#8]
When I sort by descending date, the day order is correct but within a given day the time is in asc order. I could find no way to order actions in anti-chronological order (most recents first).
I would also argue it should be the default sorting order.

Edit: if I set _time desc_ (two clicks on 'date') then _date desc_ (two clicks on 'date') I can get an anti-chronological order. But I find it convoluted and quite unintuitive, as nothing indicates the sorting order of multiple columns are taken into account.

<img width="529" alt="capture d ecran 2017-09-18 a 16 00 33" src="https://user-images.githubusercontent.com/193492/30545696-b03c8b9a-9c8a-11e7-8732-1eaa99696c94.png">

**Comment by texnixe** [comment]
I will have to look into this, maybe it wasn't such a good idea to separate the date and time fields after all.

**Comment by jenstornell** [comment]
Separate date with time is probably not a good idea. Many plugins do the sorting something like this `data-sort="1312312352"` and the number is the timestamp in this case (it should be easiest to sort by).

**Comment by texnixe** [comment]
Yes, the easiest to sort is by timestamp. Datatables should actually offer the possibility to sort by those two fields, but that probably needs a plugin to get right. When I get round to it I will change it to use a timestamp instead of the separate fields.

**Comment by jenstornell** [comment]
If you want to separate sort function from the table, this is interesting: http://tinysort.sjeiti.com/#sorting-tables. It's not dependent on jquery which I like. Also it's only focusing on the sort.

**Comment by texnixe** [comment]
I don't really want to mix anything into datatables, actually, that doesn't make sense. Or I would have to throw datatables out, but currently, I don't see a reason to do so. And since the Panel loads jQuery anyway, it doesn't matter. In the future, that's another story.

**Comment by texnixe** [comment]
I have combined the date and time fields now and sorting should work now. Let me know if it doesn't. Old log files will no longer be compatible because of this change.
